/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdminDataRouteImport } from './routes/admin-data'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as BoardLeagueIdRouteImport } from './routes/board/$leagueId'
import { Route as DraftLeagueIdRouteRouteImport } from './routes/draft/$leagueId/route'
import { Route as SeasonLeagueIdRouteRouteImport } from './routes/season/$leagueId/route'
import { Route as SetupLeagueIdRouteRouteImport } from './routes/setup/$leagueId/route'
import { Route as DraftLeagueIdIndexRouteImport } from './routes/draft/$leagueId/index'
import { Route as DraftLeagueIdBudgetRouteImport } from './routes/draft/$leagueId/budget'
import { Route as DraftLeagueIdDraftRouteImport } from './routes/draft/$leagueId/draft'
import { Route as DraftLeagueIdInjuriesRouteImport } from './routes/draft/$leagueId/injuries'
import { Route as DraftLeagueIdLeagueRouteImport } from './routes/draft/$leagueId/league'
import { Route as DraftLeagueIdMyTeamRouteImport } from './routes/draft/$leagueId/myTeam'
import { Route as DraftLeagueIdPlayersRouteImport } from './routes/draft/$leagueId/players'
import { Route as SeasonLeagueIdIndexRouteImport } from './routes/season/$leagueId/index'
import { Route as SeasonLeagueIdFreeAgentsRouteImport } from './routes/season/$leagueId/freeAgents'
import { Route as SeasonLeagueIdReportCardRouteImport } from './routes/season/$leagueId/reportCard'
import { Route as SeasonLeagueIdSettingsRouteImport } from './routes/season/$leagueId/settings'
import { Route as SetupLeagueIdIndexRouteImport } from './routes/setup/$leagueId/index'
import { Route as SetupLeagueIdBudgetRouteImport } from './routes/setup/$leagueId/budget'
import { Route as SetupLeagueIdInjuriesRouteImport } from './routes/setup/$leagueId/injuries'
import { Route as SetupLeagueIdKeepersRouteImport } from './routes/setup/$leagueId/keepers'
import { Route as SetupLeagueIdLeagueRouteImport } from './routes/setup/$leagueId/league'
import { Route as SetupLeagueIdPlayersRouteImport } from './routes/setup/$leagueId/players'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDataRoute = AdminDataRouteImport.update({
  id: '/admin-data',
  path: '/admin-data',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardLeagueIdRoute = BoardLeagueIdRouteImport.update({
  id: '/board/$leagueId',
  path: '/board/$leagueId',
  getParentRoute: () => rootRouteImport,
} as any)
const DraftLeagueIdRouteRoute = DraftLeagueIdRouteRouteImport.update({
  id: '/draft/$leagueId',
  path: '/draft/$leagueId',
  getParentRoute: () => rootRouteImport,
} as any)
const SeasonLeagueIdRouteRoute = SeasonLeagueIdRouteRouteImport.update({
  id: '/season/$leagueId',
  path: '/season/$leagueId',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupLeagueIdRouteRoute = SetupLeagueIdRouteRouteImport.update({
  id: '/setup/$leagueId',
  path: '/setup/$leagueId',
  getParentRoute: () => rootRouteImport,
} as any)
const DraftLeagueIdIndexRoute = DraftLeagueIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DraftLeagueIdRouteRoute,
} as any)
const DraftLeagueIdBudgetRoute = DraftLeagueIdBudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => DraftLeagueIdRouteRoute,
} as any)
const DraftLeagueIdDraftRoute = DraftLeagueIdDraftRouteImport.update({
  id: '/draft',
  path: '/draft',
  getParentRoute: () => DraftLeagueIdRouteRoute,
} as any)
const DraftLeagueIdInjuriesRoute = DraftLeagueIdInjuriesRouteImport.update({
  id: '/injuries',
  path: '/injuries',
  getParentRoute: () => DraftLeagueIdRouteRoute,
} as any)
const DraftLeagueIdLeagueRoute = DraftLeagueIdLeagueRouteImport.update({
  id: '/league',
  path: '/league',
  getParentRoute: () => DraftLeagueIdRouteRoute,
} as any)
const DraftLeagueIdMyTeamRoute = DraftLeagueIdMyTeamRouteImport.update({
  id: '/myTeam',
  path: '/myTeam',
  getParentRoute: () => DraftLeagueIdRouteRoute,
} as any)
const DraftLeagueIdPlayersRoute = DraftLeagueIdPlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => DraftLeagueIdRouteRoute,
} as any)
const SeasonLeagueIdIndexRoute = SeasonLeagueIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SeasonLeagueIdRouteRoute,
} as any)
const SeasonLeagueIdFreeAgentsRoute =
  SeasonLeagueIdFreeAgentsRouteImport.update({
    id: '/freeAgents',
    path: '/freeAgents',
    getParentRoute: () => SeasonLeagueIdRouteRoute,
  } as any)
const SeasonLeagueIdReportCardRoute =
  SeasonLeagueIdReportCardRouteImport.update({
    id: '/reportCard',
    path: '/reportCard',
    getParentRoute: () => SeasonLeagueIdRouteRoute,
  } as any)
const SeasonLeagueIdSettingsRoute = SeasonLeagueIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => SeasonLeagueIdRouteRoute,
} as any)
const SetupLeagueIdIndexRoute = SetupLeagueIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SetupLeagueIdRouteRoute,
} as any)
const SetupLeagueIdBudgetRoute = SetupLeagueIdBudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => SetupLeagueIdRouteRoute,
} as any)
const SetupLeagueIdInjuriesRoute = SetupLeagueIdInjuriesRouteImport.update({
  id: '/injuries',
  path: '/injuries',
  getParentRoute: () => SetupLeagueIdRouteRoute,
} as any)
const SetupLeagueIdKeepersRoute = SetupLeagueIdKeepersRouteImport.update({
  id: '/keepers',
  path: '/keepers',
  getParentRoute: () => SetupLeagueIdRouteRoute,
} as any)
const SetupLeagueIdLeagueRoute = SetupLeagueIdLeagueRouteImport.update({
  id: '/league',
  path: '/league',
  getParentRoute: () => SetupLeagueIdRouteRoute,
} as any)
const SetupLeagueIdPlayersRoute = SetupLeagueIdPlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => SetupLeagueIdRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-data': typeof AdminDataRoute
  '/billing': typeof BillingRoute
  '/draft/$leagueId': typeof DraftLeagueIdRouteRouteWithChildren
  '/season/$leagueId': typeof SeasonLeagueIdRouteRouteWithChildren
  '/setup/$leagueId': typeof SetupLeagueIdRouteRouteWithChildren
  '/board/$leagueId': typeof BoardLeagueIdRoute
  '/draft/$leagueId/budget': typeof DraftLeagueIdBudgetRoute
  '/draft/$leagueId/draft': typeof DraftLeagueIdDraftRoute
  '/draft/$leagueId/injuries': typeof DraftLeagueIdInjuriesRoute
  '/draft/$leagueId/league': typeof DraftLeagueIdLeagueRoute
  '/draft/$leagueId/myTeam': typeof DraftLeagueIdMyTeamRoute
  '/draft/$leagueId/players': typeof DraftLeagueIdPlayersRoute
  '/season/$leagueId/freeAgents': typeof SeasonLeagueIdFreeAgentsRoute
  '/season/$leagueId/reportCard': typeof SeasonLeagueIdReportCardRoute
  '/season/$leagueId/settings': typeof SeasonLeagueIdSettingsRoute
  '/setup/$leagueId/budget': typeof SetupLeagueIdBudgetRoute
  '/setup/$leagueId/injuries': typeof SetupLeagueIdInjuriesRoute
  '/setup/$leagueId/keepers': typeof SetupLeagueIdKeepersRoute
  '/setup/$leagueId/league': typeof SetupLeagueIdLeagueRoute
  '/setup/$leagueId/players': typeof SetupLeagueIdPlayersRoute
  '/draft/$leagueId/': typeof DraftLeagueIdIndexRoute
  '/season/$leagueId/': typeof SeasonLeagueIdIndexRoute
  '/setup/$leagueId/': typeof SetupLeagueIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-data': typeof AdminDataRoute
  '/billing': typeof BillingRoute
  '/board/$leagueId': typeof BoardLeagueIdRoute
  '/draft/$leagueId/budget': typeof DraftLeagueIdBudgetRoute
  '/draft/$leagueId/draft': typeof DraftLeagueIdDraftRoute
  '/draft/$leagueId/injuries': typeof DraftLeagueIdInjuriesRoute
  '/draft/$leagueId/league': typeof DraftLeagueIdLeagueRoute
  '/draft/$leagueId/myTeam': typeof DraftLeagueIdMyTeamRoute
  '/draft/$leagueId/players': typeof DraftLeagueIdPlayersRoute
  '/season/$leagueId/freeAgents': typeof SeasonLeagueIdFreeAgentsRoute
  '/season/$leagueId/reportCard': typeof SeasonLeagueIdReportCardRoute
  '/season/$leagueId/settings': typeof SeasonLeagueIdSettingsRoute
  '/setup/$leagueId/budget': typeof SetupLeagueIdBudgetRoute
  '/setup/$leagueId/injuries': typeof SetupLeagueIdInjuriesRoute
  '/setup/$leagueId/keepers': typeof SetupLeagueIdKeepersRoute
  '/setup/$leagueId/league': typeof SetupLeagueIdLeagueRoute
  '/setup/$leagueId/players': typeof SetupLeagueIdPlayersRoute
  '/draft/$leagueId': typeof DraftLeagueIdIndexRoute
  '/season/$leagueId': typeof SeasonLeagueIdIndexRoute
  '/setup/$leagueId': typeof SetupLeagueIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-data': typeof AdminDataRoute
  '/billing': typeof BillingRoute
  '/draft/$leagueId': typeof DraftLeagueIdRouteRouteWithChildren
  '/season/$leagueId': typeof SeasonLeagueIdRouteRouteWithChildren
  '/setup/$leagueId': typeof SetupLeagueIdRouteRouteWithChildren
  '/board/$leagueId': typeof BoardLeagueIdRoute
  '/draft/$leagueId/budget': typeof DraftLeagueIdBudgetRoute
  '/draft/$leagueId/draft': typeof DraftLeagueIdDraftRoute
  '/draft/$leagueId/injuries': typeof DraftLeagueIdInjuriesRoute
  '/draft/$leagueId/league': typeof DraftLeagueIdLeagueRoute
  '/draft/$leagueId/myTeam': typeof DraftLeagueIdMyTeamRoute
  '/draft/$leagueId/players': typeof DraftLeagueIdPlayersRoute
  '/season/$leagueId/freeAgents': typeof SeasonLeagueIdFreeAgentsRoute
  '/season/$leagueId/reportCard': typeof SeasonLeagueIdReportCardRoute
  '/season/$leagueId/settings': typeof SeasonLeagueIdSettingsRoute
  '/setup/$leagueId/budget': typeof SetupLeagueIdBudgetRoute
  '/setup/$leagueId/injuries': typeof SetupLeagueIdInjuriesRoute
  '/setup/$leagueId/keepers': typeof SetupLeagueIdKeepersRoute
  '/setup/$leagueId/league': typeof SetupLeagueIdLeagueRoute
  '/setup/$leagueId/players': typeof SetupLeagueIdPlayersRoute
  '/draft/$leagueId/': typeof DraftLeagueIdIndexRoute
  '/season/$leagueId/': typeof SeasonLeagueIdIndexRoute
  '/setup/$leagueId/': typeof SetupLeagueIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-data'
    | '/billing'
    | '/draft/$leagueId'
    | '/season/$leagueId'
    | '/setup/$leagueId'
    | '/board/$leagueId'
    | '/draft/$leagueId/budget'
    | '/draft/$leagueId/draft'
    | '/draft/$leagueId/injuries'
    | '/draft/$leagueId/league'
    | '/draft/$leagueId/myTeam'
    | '/draft/$leagueId/players'
    | '/season/$leagueId/freeAgents'
    | '/season/$leagueId/reportCard'
    | '/season/$leagueId/settings'
    | '/setup/$leagueId/budget'
    | '/setup/$leagueId/injuries'
    | '/setup/$leagueId/keepers'
    | '/setup/$leagueId/league'
    | '/setup/$leagueId/players'
    | '/draft/$leagueId/'
    | '/season/$leagueId/'
    | '/setup/$leagueId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin-data'
    | '/billing'
    | '/board/$leagueId'
    | '/draft/$leagueId/budget'
    | '/draft/$leagueId/draft'
    | '/draft/$leagueId/injuries'
    | '/draft/$leagueId/league'
    | '/draft/$leagueId/myTeam'
    | '/draft/$leagueId/players'
    | '/season/$leagueId/freeAgents'
    | '/season/$leagueId/reportCard'
    | '/season/$leagueId/settings'
    | '/setup/$leagueId/budget'
    | '/setup/$leagueId/injuries'
    | '/setup/$leagueId/keepers'
    | '/setup/$leagueId/league'
    | '/setup/$leagueId/players'
    | '/draft/$leagueId'
    | '/season/$leagueId'
    | '/setup/$leagueId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin-data'
    | '/billing'
    | '/draft/$leagueId'
    | '/season/$leagueId'
    | '/setup/$leagueId'
    | '/board/$leagueId'
    | '/draft/$leagueId/budget'
    | '/draft/$leagueId/draft'
    | '/draft/$leagueId/injuries'
    | '/draft/$leagueId/league'
    | '/draft/$leagueId/myTeam'
    | '/draft/$leagueId/players'
    | '/season/$leagueId/freeAgents'
    | '/season/$leagueId/reportCard'
    | '/season/$leagueId/settings'
    | '/setup/$leagueId/budget'
    | '/setup/$leagueId/injuries'
    | '/setup/$leagueId/keepers'
    | '/setup/$leagueId/league'
    | '/setup/$leagueId/players'
    | '/draft/$leagueId/'
    | '/season/$leagueId/'
    | '/setup/$leagueId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AdminDataRoute: typeof AdminDataRoute
  BillingRoute: typeof BillingRoute
  DraftLeagueIdRouteRoute: typeof DraftLeagueIdRouteRouteWithChildren
  SeasonLeagueIdRouteRoute: typeof SeasonLeagueIdRouteRouteWithChildren
  SetupLeagueIdRouteRoute: typeof SetupLeagueIdRouteRouteWithChildren
  BoardLeagueIdRoute: typeof BoardLeagueIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-data': {
      id: '/admin-data'
      path: '/admin-data'
      fullPath: '/admin-data'
      preLoaderRoute: typeof AdminDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board/$leagueId': {
      id: '/board/$leagueId'
      path: '/board/$leagueId'
      fullPath: '/board/$leagueId'
      preLoaderRoute: typeof BoardLeagueIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/draft/$leagueId': {
      id: '/draft/$leagueId'
      path: '/draft/$leagueId'
      fullPath: '/draft/$leagueId'
      preLoaderRoute: typeof DraftLeagueIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/season/$leagueId': {
      id: '/season/$leagueId'
      path: '/season/$leagueId'
      fullPath: '/season/$leagueId'
      preLoaderRoute: typeof SeasonLeagueIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/$leagueId': {
      id: '/setup/$leagueId'
      path: '/setup/$leagueId'
      fullPath: '/setup/$leagueId'
      preLoaderRoute: typeof SetupLeagueIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/draft/$leagueId/': {
      id: '/draft/$leagueId/'
      path: '/'
      fullPath: '/draft/$leagueId/'
      preLoaderRoute: typeof DraftLeagueIdIndexRouteImport
      parentRoute: typeof DraftLeagueIdRouteRoute
    }
    '/draft/$leagueId/budget': {
      id: '/draft/$leagueId/budget'
      path: '/budget'
      fullPath: '/draft/$leagueId/budget'
      preLoaderRoute: typeof DraftLeagueIdBudgetRouteImport
      parentRoute: typeof DraftLeagueIdRouteRoute
    }
    '/draft/$leagueId/draft': {
      id: '/draft/$leagueId/draft'
      path: '/draft'
      fullPath: '/draft/$leagueId/draft'
      preLoaderRoute: typeof DraftLeagueIdDraftRouteImport
      parentRoute: typeof DraftLeagueIdRouteRoute
    }
    '/draft/$leagueId/injuries': {
      id: '/draft/$leagueId/injuries'
      path: '/injuries'
      fullPath: '/draft/$leagueId/injuries'
      preLoaderRoute: typeof DraftLeagueIdInjuriesRouteImport
      parentRoute: typeof DraftLeagueIdRouteRoute
    }
    '/draft/$leagueId/league': {
      id: '/draft/$leagueId/league'
      path: '/league'
      fullPath: '/draft/$leagueId/league'
      preLoaderRoute: typeof DraftLeagueIdLeagueRouteImport
      parentRoute: typeof DraftLeagueIdRouteRoute
    }
    '/draft/$leagueId/myTeam': {
      id: '/draft/$leagueId/myTeam'
      path: '/myTeam'
      fullPath: '/draft/$leagueId/myTeam'
      preLoaderRoute: typeof DraftLeagueIdMyTeamRouteImport
      parentRoute: typeof DraftLeagueIdRouteRoute
    }
    '/draft/$leagueId/players': {
      id: '/draft/$leagueId/players'
      path: '/players'
      fullPath: '/draft/$leagueId/players'
      preLoaderRoute: typeof DraftLeagueIdPlayersRouteImport
      parentRoute: typeof DraftLeagueIdRouteRoute
    }
    '/season/$leagueId/': {
      id: '/season/$leagueId/'
      path: '/'
      fullPath: '/season/$leagueId/'
      preLoaderRoute: typeof SeasonLeagueIdIndexRouteImport
      parentRoute: typeof SeasonLeagueIdRouteRoute
    }
    '/season/$leagueId/freeAgents': {
      id: '/season/$leagueId/freeAgents'
      path: '/freeAgents'
      fullPath: '/season/$leagueId/freeAgents'
      preLoaderRoute: typeof SeasonLeagueIdFreeAgentsRouteImport
      parentRoute: typeof SeasonLeagueIdRouteRoute
    }
    '/season/$leagueId/reportCard': {
      id: '/season/$leagueId/reportCard'
      path: '/reportCard'
      fullPath: '/season/$leagueId/reportCard'
      preLoaderRoute: typeof SeasonLeagueIdReportCardRouteImport
      parentRoute: typeof SeasonLeagueIdRouteRoute
    }
    '/season/$leagueId/settings': {
      id: '/season/$leagueId/settings'
      path: '/settings'
      fullPath: '/season/$leagueId/settings'
      preLoaderRoute: typeof SeasonLeagueIdSettingsRouteImport
      parentRoute: typeof SeasonLeagueIdRouteRoute
    }
    '/setup/$leagueId/': {
      id: '/setup/$leagueId/'
      path: '/'
      fullPath: '/setup/$leagueId/'
      preLoaderRoute: typeof SetupLeagueIdIndexRouteImport
      parentRoute: typeof SetupLeagueIdRouteRoute
    }
    '/setup/$leagueId/budget': {
      id: '/setup/$leagueId/budget'
      path: '/budget'
      fullPath: '/setup/$leagueId/budget'
      preLoaderRoute: typeof SetupLeagueIdBudgetRouteImport
      parentRoute: typeof SetupLeagueIdRouteRoute
    }
    '/setup/$leagueId/injuries': {
      id: '/setup/$leagueId/injuries'
      path: '/injuries'
      fullPath: '/setup/$leagueId/injuries'
      preLoaderRoute: typeof SetupLeagueIdInjuriesRouteImport
      parentRoute: typeof SetupLeagueIdRouteRoute
    }
    '/setup/$leagueId/keepers': {
      id: '/setup/$leagueId/keepers'
      path: '/keepers'
      fullPath: '/setup/$leagueId/keepers'
      preLoaderRoute: typeof SetupLeagueIdKeepersRouteImport
      parentRoute: typeof SetupLeagueIdRouteRoute
    }
    '/setup/$leagueId/league': {
      id: '/setup/$leagueId/league'
      path: '/league'
      fullPath: '/setup/$leagueId/league'
      preLoaderRoute: typeof SetupLeagueIdLeagueRouteImport
      parentRoute: typeof SetupLeagueIdRouteRoute
    }
    '/setup/$leagueId/players': {
      id: '/setup/$leagueId/players'
      path: '/players'
      fullPath: '/setup/$leagueId/players'
      preLoaderRoute: typeof SetupLeagueIdPlayersRouteImport
      parentRoute: typeof SetupLeagueIdRouteRoute
    }
  }
}

interface DraftLeagueIdRouteRouteChildren {
  DraftLeagueIdBudgetRoute: typeof DraftLeagueIdBudgetRoute
  DraftLeagueIdDraftRoute: typeof DraftLeagueIdDraftRoute
  DraftLeagueIdInjuriesRoute: typeof DraftLeagueIdInjuriesRoute
  DraftLeagueIdLeagueRoute: typeof DraftLeagueIdLeagueRoute
  DraftLeagueIdMyTeamRoute: typeof DraftLeagueIdMyTeamRoute
  DraftLeagueIdPlayersRoute: typeof DraftLeagueIdPlayersRoute
  DraftLeagueIdIndexRoute: typeof DraftLeagueIdIndexRoute
}

const DraftLeagueIdRouteRouteChildren: DraftLeagueIdRouteRouteChildren = {
  DraftLeagueIdBudgetRoute: DraftLeagueIdBudgetRoute,
  DraftLeagueIdDraftRoute: DraftLeagueIdDraftRoute,
  DraftLeagueIdInjuriesRoute: DraftLeagueIdInjuriesRoute,
  DraftLeagueIdLeagueRoute: DraftLeagueIdLeagueRoute,
  DraftLeagueIdMyTeamRoute: DraftLeagueIdMyTeamRoute,
  DraftLeagueIdPlayersRoute: DraftLeagueIdPlayersRoute,
  DraftLeagueIdIndexRoute: DraftLeagueIdIndexRoute,
}

const DraftLeagueIdRouteRouteWithChildren =
  DraftLeagueIdRouteRoute._addFileChildren(DraftLeagueIdRouteRouteChildren)

interface SeasonLeagueIdRouteRouteChildren {
  SeasonLeagueIdFreeAgentsRoute: typeof SeasonLeagueIdFreeAgentsRoute
  SeasonLeagueIdReportCardRoute: typeof SeasonLeagueIdReportCardRoute
  SeasonLeagueIdSettingsRoute: typeof SeasonLeagueIdSettingsRoute
  SeasonLeagueIdIndexRoute: typeof SeasonLeagueIdIndexRoute
}

const SeasonLeagueIdRouteRouteChildren: SeasonLeagueIdRouteRouteChildren = {
  SeasonLeagueIdFreeAgentsRoute: SeasonLeagueIdFreeAgentsRoute,
  SeasonLeagueIdReportCardRoute: SeasonLeagueIdReportCardRoute,
  SeasonLeagueIdSettingsRoute: SeasonLeagueIdSettingsRoute,
  SeasonLeagueIdIndexRoute: SeasonLeagueIdIndexRoute,
}

const SeasonLeagueIdRouteRouteWithChildren =
  SeasonLeagueIdRouteRoute._addFileChildren(SeasonLeagueIdRouteRouteChildren)

interface SetupLeagueIdRouteRouteChildren {
  SetupLeagueIdBudgetRoute: typeof SetupLeagueIdBudgetRoute
  SetupLeagueIdInjuriesRoute: typeof SetupLeagueIdInjuriesRoute
  SetupLeagueIdKeepersRoute: typeof SetupLeagueIdKeepersRoute
  SetupLeagueIdLeagueRoute: typeof SetupLeagueIdLeagueRoute
  SetupLeagueIdPlayersRoute: typeof SetupLeagueIdPlayersRoute
  SetupLeagueIdIndexRoute: typeof SetupLeagueIdIndexRoute
}

const SetupLeagueIdRouteRouteChildren: SetupLeagueIdRouteRouteChildren = {
  SetupLeagueIdBudgetRoute: SetupLeagueIdBudgetRoute,
  SetupLeagueIdInjuriesRoute: SetupLeagueIdInjuriesRoute,
  SetupLeagueIdKeepersRoute: SetupLeagueIdKeepersRoute,
  SetupLeagueIdLeagueRoute: SetupLeagueIdLeagueRoute,
  SetupLeagueIdPlayersRoute: SetupLeagueIdPlayersRoute,
  SetupLeagueIdIndexRoute: SetupLeagueIdIndexRoute,
}

const SetupLeagueIdRouteRouteWithChildren =
  SetupLeagueIdRouteRoute._addFileChildren(SetupLeagueIdRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AdminDataRoute: AdminDataRoute,
  BillingRoute: BillingRoute,
  DraftLeagueIdRouteRoute: DraftLeagueIdRouteRouteWithChildren,
  SeasonLeagueIdRouteRoute: SeasonLeagueIdRouteRouteWithChildren,
  SetupLeagueIdRouteRoute: SetupLeagueIdRouteRouteWithChildren,
  BoardLeagueIdRoute: BoardLeagueIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
